title: "Introduction to Git and GitHub"
theme: jekyll-theme-modernist
color_scheme: "nil"
search_enabled: false
aux_links:
  "UBC Library Research Commons Workshops":
    - "https://researchcommons.library.ubc.ca/workshops/"
heading_anchors: false
footer_content: "Copyright &copy UBC Library Research Commons. Adapted from <a href=\"https://librarycarpentry.org/lc-git/\">Library Carpentry: Introduction to Git</a> and <a href=\"https://swcarpentry.github.io/git-novice/08-collab/index.html\">Software Carpentry: Version Control with Git</a>. All material licensed <a href=\"https://creativecommons.org/licenses/by/4.0\">Creative Commons Attribution 4.0</a>."
